/* GATA Cloud Uploader - central configuration.
 * Also loaded by the service worker (sw.js) via importScripts, so keep it
 * dependency-free and side-effect-free.
 */
"use strict";

const APP_CONFIG = {
  version: "2.31.0",                   // bump on every deploy (drives the offline cache)
  /* Customer channel this copy belongs to. Customer packages are generated by
   * tools\new_customer.ps1, which pins the id here and points cloudManifestUrl
   * at that customer's signed firmware list. The id is also written INSIDE the
   * signed manifest, and the app refuses a list whose channel does not match -
   * so one customer's app can never install another customer's firmware, even
   * if the URLs were mixed up. "default" is the shared channel. */
  channel: "danway",
  customerName: "Danway",
  productName: "GATA",

  /* Where firmware comes from, tried in this order (first one that answers):
   *  1. cloudManifestUrl      - direct download. GitHub raw serves it publicly
   *     and sends Access-Control-Allow-Origin, so PCs and Android phones can
   *     fetch it with no server setup and no credentials;
   *  2. "__fw/manifest.json"  - the local server's proxy (installed app only).
   *     Covers hosts that need a token or send no CORS header - e.g. the
   *     company Gitea mirror; configure with tools\set_firmware_source.ps1;
   *  3. defaultManifestUrl    - the copy bundled in this folder (offline).
   * A BAD SIGNATURE is always fatal - it never falls through to the next one.
   * Every source is equally untrusted: only the signature decides. */
  cloudManifestUrl: "https://raw.githubusercontent.com/gata2024/gata-firmware/main/customers/danway/manifest.json",
  proxyManifestUrl: "__fw/manifest.json",
  defaultManifestUrl: "firmware/manifest.json",

  // USB identities (from USBupdaterCode descriptors / STM32 ROM)
  dfuVid: 0x0483, dfuPid: 0xDF11,         // "DFU in FS Mode" (ROM bootloader)
  cdcVid: 0x0483, cdcPid: 0x5740,         // "GATA Controller" (application and update firmware)

  // Memory layout
  systemFlashAddr: 0x08000000,            // internal flash (B1/B3)
  systemFlashMax: 128 * 1024,             // STM32H750: single 128 KB sector
  appFlashAddr: 0x90000000,               // external QSPI flash (M*.bin)
  appFlashMax: 16 * 1024 * 1024,          // W25Q128 = 16 MB

  // Behaviour
  historyMax: 20,                         // update-history entries kept
  cacheMaxFiles: 30,                      // firmware files kept in IndexedDB

  // Firmware-list signing (anti-tamper): the ECDSA P-256 PUBLIC key is pinned
  // here; manifest.json must carry a valid manifest.json.sig or the app
  // refuses the list. The matching PRIVATE key lives ONLY in
  // tools/signing_key.json on the release PC - never publish that file.
  // Managed by tools/make_signing_key.ps1 - keep this on ONE line.
  signingPublicKey: {"kty":"EC","crv":"P-256","x":"rxMOSG5w5UB7vQF8Zxo56Fa1jBTSVl5MZIO4CH6eGso","y":"hYEieTzrcSaFGoP4OhibV5VplLgv4bLGxVfJbILPdtE"},

  // License verification (one app for every customer; a signed license picks
  // the firmware channel). PUBLIC key only - the matching PRIVATE key lives
  // in tools/license_key.json on the release PC and is what mints licenses.
  // Managed by tools/make_license.ps1 - keep this on ONE line.
  licensePublicKey: {"kty":"EC","crv":"P-256","x":"Q7_kR_3kXLvNKCxmb82TkaaqiADo8SNl-degtpzEAc8","y":"jRzED7BLckFufo_2YARRIxv-_Kj7MI3kG2iGBs9Pxxc"},
};
